language: php

php:
    - 5.6

os:
    - linux

sudo: true

dist: trusty
  
git:
  depth: false
  submodules: false

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - echo "No script to run"

after_success:
  - docker login -u pipposwe -p $DOCKER_PASSWORD
  - export REPO=pipposwe/ajarvis-rest
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
